FROM centos:7

RUN yum install -y epel-release && yum install -y python-pip git iproute gcc python-devel &&  yum clean all && pip install --upgrade pip

RUN git clone https://github.com/cao19881125/ytvpn.git && cd ytvpn && pip install .

ENV TERM linux

